/** App-wide constants. */
export const APP_NAME = 'Sherin';
export const APP_PORT = 3011;

export {
  BABYSEA_MODEL_CONFIGS,
  BYOK_FAMILY,
  BYOK_INFERENCE_PROVIDER_ID,
  BYOK_INFERENCE_PROVIDER_KEYWORD,
  BYOK_INFERENCE_PROVIDER_LABEL,
  BYOK_MODEL_CONFIGS,
  BYOK_MODEL_ID_PREFIX,
  BYOK_MODEL_IDS,
  DEFAULT_BYOK_GUIDANCE,
  DEFAULT_BYOK_SAFETY_TOLERANCE,
  DEFAULT_BYOK_STEPS,
  DEFAULT_GENERATION_GUIDANCE_SCALE,
  DEFAULT_GENERATION_NUM_INFERENCE_STEPS,
  DEFAULT_GENERATION_OUTPUT_NUMBER,
  DEFAULT_GENERATION_OUTPUT_QUALITY,
  DEFAULT_MODEL_ID,
  DEFAULT_OUTPUT_FORMAT,
  DEFAULT_RATIO,
  DEFAULT_RESOLUTION,
  GENERATION_PROMPT_PLACEHOLDER,
  MODEL_IDS,
  MODEL_OPTIONS,
  OUTPUT_FORMATS,
  RATIOS,
  RATIO_OPTIONS,
  RESOLUTION_OPTIONS,
  SHERIN_INPUT_FILE_LIMIT,
  getBabySeaInputFileLimit,
  getBabySeaProviderOrderOverride,
  getDefaultModelIdForInferenceProvider,
  getModelIdsForInferenceProvider,
  getModelOptionsForInferenceProvider,
  hasByokModelConfig,
  isSherinModelId,
  isSherinResolution,
} from './model-family';

export type {
  BabySeaModelConfig,
  ByokInferenceProviderId,
  InferenceProviderScope,
  SherinDimensionRatio,
  SherinModelId,
  SherinOutputFormat,
  SherinRatio,
  SherinResolution,
} from './model-family';
